//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "bill_line")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub transaction_data: String,
    pub description_id: i32,
    pub debit: Option<f64>,
    pub credit: Option<f64>,
    pub balance: f64,
    pub raw_csv_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bill_line_description::Entity",
        from = "Column::DescriptionId",
        to = "super::bill_line_description::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    BillLineDescription,
    #[sea_orm(
        belongs_to = "super::raw_csv::Entity",
        from = "Column::RawCsvId",
        to = "super::raw_csv::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RawCsv,
}

impl Related<super::bill_line_description::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BillLineDescription.def()
    }
}

impl Related<super::raw_csv::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RawCsv.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
