//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "bill_line")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub transaction_data: String,
    pub description: String,
    pub debit: Option<f64>,
    pub credit: Option<f64>,
    pub balance: f64,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
