//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "description_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bill_line_description::Entity")]
    BillLineDescription,
}

impl Related<super::bill_line_description::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BillLineDescription.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
