//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub use super::bill_line::Entity as BillLine;
pub use super::bill_line_description::Entity as BillLineDescription;
pub use super::raw_csv::Entity as RawCsv;
